##############################################################
# Mobile Application Programming (SCSJ3623)
# Semester 2, 2019/2020
##############################################################

# REST API Server on Local Firebase
@baseUrl = http://localhost:5001/heavenly-recipe/us-central1/api

# REST API Server on Live Firebase
# @baseUrl = https://us-central1-heavenly_recipe.cloudfunctions.net/api

### Getting the list of quote
GET {{baseUrl}}/recipes

###  Getting a quote of given id
GET {{baseUrl}}/recipes/wUMvJm7XkdxHCMrNEq1z

###  Create a new quote
POST {{baseUrl}}/recipes
Content-Type: application/json

{ 
    "name": "Abdussalam", 
    "title": "Student", 
    "profileURL": "", 
    "coverURL": "", 
    "followers": [], 
    "following": [], 
    "preferences": [], 
    "recipes": [], 
    "data": { "isDarkMode": true, "notification": 0 } 
}

### Update the status of a given quote (whether is completed or not)
PATCH {{baseUrl}}/recipes/wUMvJm7XkdxHCMrNEq1z
Content-Type: application/json

{
    "name": "Amirul Danish"
}


### Replace the entire fields of a given quote
PUT {{baseUrl}}/recipes/arMF0wRHlOrYjqfhLHL5
Content-Type: application/json

{
    "name": "Nazri"
}

### Deleting a given quote
DELETE {{baseUrl}}/recipes/Us3o8G5m7LfIblD4lSSk